### ISSUE TITLE
Add api middleware to check if a user a subscribed to a valid paystack plan

### ISSUE THREAD

**Issue by purplenimbus** [purplenimbus/edu-api#51]
- [x] Create [middleware](https://laravel.com/docs/8.x/middleware#defining-middleware) `CheckSubscription` that returns **true** for now. we will check if a user has a valid paystack subscription eventually

- [x] Apply middleware to the following grouped routes
  - Terms
  - Courses
  - Lessions
  - Registrations
  - Instructors
  - Students
  - Guardians

**Comment by oshkbello** [comment]
Since there was nothing to test against. I allowed it into the application.
