### ISSUE TITLE
Add an endpoint to Terms model to create a new term for a Tenant

### ISSUE THREAD

**Issue by purplenimbus** [purplenimbus/edu-api#66]
- [x] Add a `create` method to the [TermsController](https://github.com/purplenimbus/edu-api/blob/master/app/Http/Controllers/TermController.php) to create a new [SchoolTerm](https://github.com/purplenimbus/edu-api/blob/master/app/SchoolTerm.php) 
 - [x] Create a new form [request](https://laravel.com/docs/7.x/validation#creating-form-requests) `StoreTerm` based on the following validation [rules](https://laravel.com/docs/7.x/validation#available-validation-rules)
   - **description** `nullable,string`
   - **end_date** `date`
   - **name** `nullable,string`
   - **meta** `nullable`
   - **start_date** `date`
   - **status_id** `integer,exists:term_statuses,id`
   - **tenant_id** `integer,tenants,id`
 - [x] Apply the `StoreTerm` validation to the create route
 - [x] Add a new api route for creating a new term

**Comment by oshkbello** [comment]
term_statuses is meant to be school_term_statuses. Please confirm

**Comment by purplenimbus** [comment]
> term_statuses is meant to be school_term_statuses. Please confirm

yes
